version: '3.7'

services:
  elasticsearch:
    build: ./ElasticSearch
    container_name: elasticsearch-7.0
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
    - elasticsearch_net

  kibana:
    build: ./Kibana
    container_name: kibana-7.0
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
    networks:
      - elasticsearch_net

volumes:
  elasticsearch_data:
    driver: local

networks:
  elasticsearch_net: